[project]
name = "plantpal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.54.0",
    "tensorflow>=2.20.0",
]
